test = {'name': 'q1',
        'points': 1,
        'suites': [{'cases': [{'code': '>>> qualifyForMedicare(65)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> qualifyForMedicare(64)\nFalse',
                               'hidden': False, 'locked': False},
                              {'code': '>>> qualifyForMedicare(72)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> qualifyForMedicare(18)\nFalse',
                               'hidden': False, 'locked': False}],
                    'scored': True,
                    'setup': '',
                    'teardown': '',
                    'type': 'doctest'}]}
