test = {'name': 'q2',
        'points': 1,
        'suites': [{'cases': [{'code': '>>> isEven(0)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> isEven(64)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> isEven(754)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> isEven(33)\nFalse',
                               'hidden': False, 'locked': False},
                              {'code': '>>> isEven(79)\nFalse',
                               'hidden': False, 'locked': False},
                              {'code': '>>> isEven(1)\nFalse',
                               'hidden': False, 'locked': False}],
                    'scored': True,
                    'setup': '',
                    'teardown': '',
                    'type': 'doctest'}]}
