test = {'name': 'q5',
        'points': 1,
        'suites': [{'cases': [{'code': '>>> assert summation(2, 4) == 5', 'hidden': False, 'locked': False},
                              {'code': '>>> assert summation(3, 7) == 18',
                               'hidden': False, 'locked': False},
                              {'code': '>>> assert summation(6, 1) == 0',
                               'hidden': False, 'locked': False},
                              {'code': '>>> assert summation(22, 20) == 0',
                               'hidden': False, 'locked': False},
                              {'code': '>>> assert summation(43, 73) == 1725',
                               'hidden': False, 'locked': False},
                              {'code': '>>> assert summation(33, 42) == 333',
                               'hidden': False, 'locked': False},
                              {'code': '>>> assert summation(11, 25) == 245',
                               'hidden': False, 'locked': False}],
                    'scored': True,
                    'setup': '',
                    'teardown': '',
                    'type': 'doctest'}]}
