test = {'name': 'q5',
        'points': 1,
        'suites': [{'cases': [{'code': '>>> summation(2, 4) == 5\nTrue', 'hidden': False, 'locked': False},
                              {'code': '>>> summation(3, 7) == 18\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> summation(6, 1) == 0\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> summation(22, 20) == 0\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> summation(43, 73) == 1725\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> summation(33, 42) == 333\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> summation(11, 25) == 245\nTrue',
                               'hidden': False, 'locked': False}],
                    'scored': True,
                    'setup': '',
                    'teardown': '',
                    'type': 'doctest'}]}
