test = {'name': 'q1',
        'points': 1,
        'suites': [{'cases': [{'code': '>>> quadratic(5, 6, 1) == (-0.2, -1)\nTrue', 'hidden': False, 'locked': False},
                              {'code': '>>> quadratic(2, -8, -24) == (6, -2)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> quadratic(1, -5, 6) == (3, 2)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> quadratic(1, -5, -24) == (8, -3)\nTrue',
                               'hidden': False, 'locked': False},
                              {'code': '>>> quadratic(1, 3, -10) == (2, -5)\nTrue', 'hidden': False, 'locked': False}],
                    'scored': True,
                    'setup': '',
                    'teardown': '',
                    'type': 'doctest'}]}
